name: Build and Deploy
on:
  push:
    branches:
      gen2
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.35.3

      - name: Build
        run: make clean dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gen2-pages
          folder: dist